class CfgPatches
{
	class ThorsHammer
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data"
		};
	};
};
class CfgVehicles 
{
	class PoliceBaton;
	class AMIWORTHY: PoliceBaton
	{
		scope=2;
		displayName="Mjolnir";
		descriptionShort="I call bullshit. Like hell your ass is worthy... >:(";
		model="JDweapons\Melee\ThorsHammer\ThorsHammer.p3d";
		rotationFlags=12;
		weight=750;
		itemSize[]={3,2};
		isMeleeWeapon=1;
		itemBehaviour=1;
		fragility=0.002;
		inventorySlot[]=
		{
			"Shoulder",
			"Melee"
		};
		class MeleeModes
		{
			class Default
			{
				ammo="MeleeThorHeavy";
				range=2;
			};
			class Heavy
			{
				ammo="MeleeThorHeavy";
				range=2;
			};
			class Sprint
			{
				ammo="MeleeThorHeavy";
				range=4.0999999;
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=200000;
					healthLevels[]=
					{
						
						{
							1.0,
							
							{
								"DZ\gear\cooking\data\frying_pan.rvmat"
							}
						},
						
						{
							0.7,
							
							{
								"DZ\gear\cooking\data\frying_pan.rvmat"
							}
						},
						
						{
							0.5,
							
							{
								"DZ\gear\cooking\data\frying_pan_damage.rvmat"
							}
						},
						
						{
							0.3,
							
							{
								"DZ\gear\cooking\data\frying_pan_damage.rvmat"
							}
						},
						
						{
							0.0,
							
							{
								"DZ\gear\cooking\data\frying_pan_destruct.rvmat"
							}
						}
					};
				};
			};
		};
	};
};
	
class CfgAmmo
{
	class MeleeDamage;
	class MeleeThorHeavy: MeleeDamage
	{
		affectSkeleton=1.4;
		class DamageApplied
		{
			type="Melee";
			bleedThreshold=1;
			class Health
			{
				damage=125;
			};
			class Blood
			{
				damage=0;
			};
			class Shock
			{
				damage=2000;
			};
			additionAnimalMeleeMultiplier=2;
		};
		soundGroundSoft1[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONG",
			1.6,
			1,
			1000
		};
		soundGroundSoft2[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONG2",
			1.6,
			1,
			1000
		};
		soundGroundSoft3[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONG3",
			1.6,
			1,
			1000
		};
		soundGroundSoft4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGroundSoft[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGroundHard[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMan[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitArmor[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitBuilding[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitFoliage[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitWood[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGlass[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGlassArmored[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitConcrete[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitRubber[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitPlastic[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitDefault[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMetal[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMetalplate[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitWater[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
	};
	class MeleeThorLight: MeleeDamage
	{
		affectSkeleton=1.4;
		class DamageApplied
		{
			type="Melee";
			bleedThreshold=1;
			class Health
			{
				damage=130;
			};
			class Blood
			{
				damage=0;
			};
			class Shock
			{
				damage=2000;
			};
			additionAnimalMeleeMultiplier=2;
		};
		soundGroundSoft1[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONGlight",
			1.5,
			1,
			1000
		};
		soundGroundSoft2[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONGlight",
			1.5,
			1,
			1000
		};
		soundGroundSoft3[]=
		{
			"JDweapons\Melee\ThorsHammer\sounds\BONGlight",
			1.5,
			1,
			1000
		};
		soundGroundSoft4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundSoft8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGroundHard8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundMetal8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitGlass6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundGlassArmored6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundVehiclePlate8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWood8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBody6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitBuilding8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundHitFoliage4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundPlastic4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete5[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete6[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete7[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundConcrete8[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundRubber4[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater1[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater2[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		soundWater3[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGroundSoft[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGroundHard[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMan[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitArmor[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitBuilding[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitFoliage[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitWood[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGlass[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitGlassArmored[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitConcrete[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitRubber[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitPlastic[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitDefault[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMetal[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitMetalplate[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
		hitWater[]=
		{
			"soundGroundSoft1",0.2,"soundGroundSoft2",0.2,"soundGroundSoft3",0.1
		};
	};
};	